# Generated by Django 3.2.4 on 2021-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_files_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
