# Generated by Django 3.2.4 on 2021-06-09 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shared',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_file', to='app.files'),
        ),
    ]
